---
openapi: 3.0.2
info:
  title: Todo List
  version: 1.0.0
  description: Todo List Spec
paths:
  /items:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
              examples:
                items:
                  value:
                  - id: "123123"
                    name: Buy Bananas
                    description: Buy Bananas
                  - id: "345345"
                    name: Buy Chocolate
                    description: 85% chocolate
          description: valid Response
      operationId: getItems
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
            examples:
              item:
                value:
                  id: "123123"
                  name: Buy Bananas
                  description: Buy Bananas
        required: true
      responses:
        "201":
          description: Created description
      operationId: createItem
components:
  schemas:
    Item:
      title: Root Type for Item
      description: Item type
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
      example:
        id: "3423432432"
        name: Bananas
        description: Buy bananas at Carrefour
  securitySchemes:
    api-key:
      type: apiKey
      description: Use a 3scale API Key
      name: api-key
      in: header
security:
    -
        api-key: []
